### ISSUE TITLE
Cant register

### ISSUE THREAD

**Issue by gbdavidx** [JPHutchins/pgesmd_self_access#4]
When trying to register i get the following errors

```
Type "help", "copyright", "credits" or "license" for more information.
>>> from pgesmd_self_access.api import PgeRegister
>>> pge_reg = PgeRegister()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/pgesmd_self_access/pgesmd_self_access/api.py", line 367, in __init__
    self.auth = method(auth_path)
  File "/home/david/pgesmd_self_access/pgesmd_self_access/helpers.py", line 21, in get_auth_file
    json_data = json.loads(data)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 3 (char 28)
>>> pge_reg = PgeRegister()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/pgesmd_self_access/pgesmd_self_access/api.py", line 367, in __init__
    self.auth = method(auth_path)
  File "/home/david/pgesmd_self_access/pgesmd_self_access/helpers.py", line 21, in get_auth_file
    json_data = json.loads(data)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 3 (char 28)
>>> pge_reg = PgeRegister
```

**Comment by gbdavidx** [comment]
<img width="904" alt="Screen Shot 2022-04-14 at 9 43 04 PM" src="https://user-images.githubusercontent.com/26369204/163519481-3e4e04e2-5e75-4461-b31e-938c6df5a640.png">
<img width="645" alt="Screen Shot 2022-04-14 at 9 43 23 PM" src="https://user-images.githubusercontent.com/26369204/163519505-58d0eb99-c7fd-43a4-8797-7ce8f4833532.png">
dependancies have been installed and running in python environment
